#server configuration
server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice
    username: root
    password: root

  jpa:
#    hibernate:
#      ddl-auto: create

    properties:
      hibernate.format_sql: true
    show-sql: true
